config/routes.rb
Rails.application.routes.draw do

  
  get 'about' => 'welcome#about'
  
  root 'welcome#index'

  
  resources :wikis

  
  resources :users, only: [:new, :create]
  
  resources :sessions, only: [:new, :create, :destroy]

end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :wikis, dependent: :destroy
    
    before_save { self.email = email.downcase if email.present? }

    validates :name, length: { minimum: 1, maximum: 100 }, presence: true
    validates :password, presence: true, length: { minimum: 6 }
    validates :password, length: { minimum: 6 }, allow_blank: true
    validates :email,
             presence: true,
             uniqueness: { case_sensitive: false },
             length: { minimum: 3, maximum: 254 }

end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
   belongs_to :user

   validates :title, length: { minimum: 10 }, presence: true
   validates :body, length: { minimum: 80 }, presence: true
   validates :user, presence: true
   
   default_scope { order('created_at DESC') }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
  
  private
  
   def require_sign_in
     unless current_user
       flash[:alert] = "You must be logged in to do that"
       redirect_to new_session_path
     end
   end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def confirm
     @user = User.new
     @user.name = params[:user][:name]
     @user.email = params[:user][:email]
     @user.password = params[:user][:password]
     @user.password_confirmation = params[:user][:password_confirmation]
  end
  
  def create
    
    @user = User.new
    @user.name = params[:user][:name]
    @user.email = params[:user][:email]
    @user.password = params[:user][:password]
    @user.password_confirmation = params[:user][:password_confirmation]
 
    if @user.save
      flash[:notice] = "Welcome to Blocipedia #{@user.name}!"
      create_session(@user)
      redirect_to root_path
    else
      flash.now[:alert] = "There was an error creating your account. Please try again."
      render :new
    end
  end

  def confirm
  end

  def show
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
    
  before_action :require_sign_in, except: [:show, :index]
  
  def new
   @wiki = Wiki.new
  end
  
  def create
     #@wiki = Wiki.new
     #@wiki.title = params[:wiki][:title]
     #@wiki.body = params[:wiki][:body]
     @wiki = @wiki.build(post_params)
     @wiki.user = current_user

    if @wiki.save
       flash[:notice] = "Wiki was saved successfully."
       redirect_to @wiki
    else
       flash.now[:alert] = "There was an error saving the wiki. Please try again."
       render :new
    end
  end
  
  def update
     @wiki = Wiki.find(params[:id])
     #@wiki.title = params[:wiki][:title]
     #@wiki.body = params[:wiki][:body]
     @wiki.assign_attributes(post_params)
 
     if @wiki.save
       flash[:notice] = "Wiki was updated successfully."
       redirect_to @wiki
     else
       flash.now[:alert] = "There was an error saving the wiki. Please try again."
       render :edit
     end
  end
  
  def destroy
     @wiki = Wiki.find(params[:id])
 
     if @wiki.destroy
       flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
       redirect_to wikis_path
     else
       flash.now[:alert] = "There was an error deleting the wiki."
       render :show
     end
   end

  def edit
    @wiki = Wiki.find(params[:id])
  end

  def index
    @wikis = Wiki.all
  end

  def show
     @wiki = Wiki.find(params[:id])
  end
  
  private
 
   def post_params
     params.require(:wiki).permit(:title, :body)
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
     def form_group_tag(errors, &block)
     css_class = 'form-group'
     css_class << ' has-error' if errors.any?
     content_tag :div, capture(&block), class: css_class
   end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
 <html>
 <head>
   <title>Bloccit</title>
   <%= stylesheet_link_tag    "application", media: "all" %>
   <%= javascript_include_tag "application" %>
   <%= csrf_meta_tags %>
 </head>
 <body>
   <ul>
       <li><%= link_to "Blocipedia", root_path %></li>
       <li><%= link_to "About", about_path %></li>
       
       <div class="pull-right user-info">
         <% if current_user %>
           <%= current_user.name %> - <%= link_to "Sign Out", session_path(current_user), method: :delete %>
         <% else %>
           <%= link_to "Sign In", new_session_path %> or
           <%= link_to "Sign Up", new_user_path %>
         <% end %>
       </div>
   </ul>
      
      
   <% if flash[:notice] %>
       <div class="alert alert-success">
         <button type="button" class="close" data-dismiss="alert">&times;</button>
         <%= flash[:notice] %>
       </div>
   <% elsif flash.now[:alert] %>
       <div class="alert alert-danger">
         <button type="button" class="close" data-dismiss="alert">&times;</button>
         <%= flash.now[:alert] %>
       </div>
   <% elsif flash[:alert] %>
       <div class="alert alert-warning">
         <button type="button" class="close" data-dismiss="alert">&times;</button>
         <%= flash[:alert] %>
       </div>
   <% end %>
   
   <%= yield %>

 </body>
 </html>

app/views/layouts/wikis/edit.html.erb
<h1>Edit Wiki</h1>
 
 <div class="row">
   <div class="col-md-4">
     <p>Guidelines for wikis</p>
     <ul>
       <li>Stay on point.</li>
       <li>Use any letter in the alphabet you wish to use.</li>
       <li>The incessant use of editing will get you banned.</li>
     </ul>
   </div>
   <div class="col-md-8">
     <%= form_for @wiki do |f| %>
     <% if wiki.errors.any? %>
     <div class="alert alert-danger">
       <h4><%= pluralize(wiki.errors.count, "error") %>.</h4>
       <ul>
         <% wiki.errors.full_messages.each do |msg| %>
           <li><%= msg %></li>
         <% end %>
       </ul>
     </div>
     <% end %>
     <%= form_group_tag(wiki.errors[:title]) do %>
         <%= f.label :title %>
         <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
     <% end %>
     <%= form_group_tag(post.errors[:body]) do %>
         <%= f.label :body %>
         <%= f.text_area :body, rows: 16, class: 'form-control', placeholder: "Enter wiki body" %>
     <% end %>
       <div class="form-group">
         <%= f.submit "Save", class: 'btn btn-success' %>
       </div>
     <% end %>
   </div>
 </div>

app/views/layouts/wikis/index.html.erb
<h1>All Wikis</h1>

 <% @wikis.each do |wiki| %>
     <div class="media">
     <div class="media-body">
       <h4 class="media-heading">
         <%= link_to wiki.title, wiki %>
       </h4>
     </div>
   </div>
 <% end %>

app/views/layouts/wikis/new.html.erb
<h1>New Wiki</h1>
 
 <div class="row">
   <div class="col-md-4">
     <p>Guidelines for wikis</p>
     <ul>
       <li>Stay on point.</li>
       <li>Use any letter in the alphabet you wish to use.</li>
       <li>The incessant use of editing will get you banned.</li>
     </ul>
   </div>
   <div class="col-md-8">
     <%= form_for @wiki do |f| %>
     <% if wiki.errors.any? %>
     <div class="alert alert-danger">
       <h4><%= pluralize(wiki.errors.count, "error") %>.</h4>
       <ul>
         <% wiki.errors.full_messages.each do |msg| %>
           <li><%= msg %></li>
         <% end %>
       </ul>
     </div>
     <% end %>
     <%= form_group_tag(wiki.errors[:title]) do %>
         <%= f.label :title %>
         <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
     <% end %>
     <%= form_group_tag(wiki.errors[:body]) do %>
         <%= f.label :body %>
         <%= f.text_area :body, rows: 16, class: 'form-control', placeholder: "Enter wiki body" %>
     <% end %>
       <div class="form-group">
         <%= f.submit "Save", class: 'btn btn-success' %>
       </div>
     <% end %>
   </div>
 </div>

app/views/layouts/wikis/show.html.erb
 <h1>
   <%= @wiki.title %> <br>
   <small>
     submitted <%= time_ago_in_words(@wiki.created_at) %> ago by <%= @wiki.user.name %>
   </small>
 </h1>
 
 <div class="row">
   <div class="col-md-8">
     <p><%= @wiki.body %></p>
   </div>
   <div class="col-md-4">
     <%= link_to "Edit", edit_wiki_path(@wiki), class: 'btn btn-success' %>
     <%= link_to "Delete Wiki", @wiki, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this wiki?'} %>
   </div>
 </div>

app/views/users/confirm.html.erb
<h2>Sign Up Confirmation</h2>

<div class = "row">
  <div class = "col-md-4">
    <h4>Are you sure these values are correct?</h4>
    <h5>Email: <% @user.email %></h5>
    <h5>Name: <% @user.name %></h5>
  </div>
</div>

<div class = "row">
  <div class = "col-md 4", style = "width: auto;">
    <%= button_to "Yes", {controller: "users", action: "create", params: params}, class: 'btn btn-success' %>
  </div>
  <div class = "col-md 4", style = "width: auto;">
    <%= button_to "No", {controller: "users", action: "new"}, class: 'btn btn-failure', :method => :get %>
  </div>
</div>

app/views/users/new.html.erb
 <h2>Sign up</h2>
 
 <div class="row">
   <div class="col-md-8">
     <%= form_for @user do |f| %>
       <% if @user.errors.any? %>
         <div class="alert alert-danger">
           <h4><%= pluralize(@user.errors.count, "error") %>.</h4>
           <ul>
             <% @user.errors.full_messages.each do |msg| %>
               <li><%= msg %></li>
             <% end %>
           </ul>
         </div>
       <% end %>
       <%= form_group_tag(@user.errors[:name]) do %>
         <%= f.label :name %>
         <%= f.text_field :name, autofocus: true, class: 'form-control', placeholder: "Enter name" %>
       <% end %>
       <%= form_group_tag(@user.errors[:email]) do %>
         <%= f.label :email %>
         <%= f.email_field :email, class: 'form-control', placeholder: "Enter email" %>
       <% end %>
       <%= form_group_tag(@user.errors[:password]) do %>
         <%= f.label :password %>
         <%= f.password_field :password, class: 'form-control', placeholder: "Enter password" %>
       <% end %>
       <%= form_group_tag(@user.errors[:password_confirmation]) do %>
         <%= f.label :password_confirmation %>
         <%= f.password_field :password_confirmation, class: 'form-control', placeholder: "Enter password confirmation" %>
       <% end %>
       <div class="form-group">
         <%= f.submit "Sign up", class: 'btn btn-success' %>
       </div>
     <% end %>
   </div>
 </div>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

app/views/welcome/about.html.erb
<h1>About Blocipedia</h1>
 <p>Created by: Me</p>

app/views/welcome/index.html.erb
 <br>
 <div class="jumbotron">
   <h1>Blocipedia</h1>
   <p>Blocipedia is a resource for collaborating on wikis!</p>
   <p>
     <%= link_to "Sign In", new_session_path %> or
     <%= link_to "Sign Up", new_user_path, class: 'btn btn-primary' %> today!
   </p>
 </div>